### ISSUE TITLE
Deal with new '--version' conflict with (default) 'build --version'

### ISSUE THREAD

**Issue by altendky** [twisted/towncrier#344]
https://github.com/twisted/towncrier/pull/341#issuecomment-821226041

**Comment by hmaarrfk** [comment]
It wasn't fun to hit this today.

I guess take my comment as a user story.


I've already updated my scripts.

**Comment by hmaarrfk** [comment]
For those that don't know, this landed in the official release:

> towncrier 21.9.0 (2022-02-04)

**Comment by adiroiban** [comment]
Fixed in #341

**Comment by hmaarrfk** [comment]
I'm not sure why this issue is closed.

It is about ensuring backward compatibility that was broken in #341

**Comment by adiroiban** [comment]
Thanks for  the info.

I know that breaking backward compatibility is no joy...

And this is mainly my fault.

But, at this point, I don't know what we can do.

`--version` was already released to return the towncrier version.

The right thing to do had been to revert #341 ...but I think that now is too late.


Release 21.9.0 https://github.com/twisted/towncrier/pull/360 was waiting for feedback since October last year...and nobody asked for the released to be block

I guess the lesson learned it to use GitHub  Releases for the pre-release and anyone interested can subscribe to the release RSS

----

I am kind of an emergency release manager now... I am using towncrier, but since 2017 it just works and I don't have to upgrade.

I am kind of an emergency release manager now.

So, if anyone has some extra time, it  would help to get a fully dedicated release manager for towncrier.

----------

If anyone can come with a way to fix it now, I am happy to reopen it and merge such a PR.

For now, I think that this is closed as won't fix...and I don't know how we can fix it.

Cheers

**Comment by hmaarrfk** [comment]
That's fine. I think your explanation is mostly a "won't fix" and explains it quite well.

**Comment by hmaarrfk** [comment]
```
towncrier build --version x.y.z
```

**Comment by acabarbaye** [comment]
Could this be added to the readme as it is not clearly explained there:
```
towncrier needs to know what version your project is, and there are three ways you can give it:

    For Python 2/3 compatible projects, a __version__ in the top level package. This can be either a string literal, a tuple, or an [Incremental](https://github.com/hawkowl/incremental) version.
    Manually passing --version=<myversionhere> when interacting with towncrier.
    Definining a version option in a configuration file:
```
