### ISSUE TITLE
Github releases integration

### ISSUE THREAD

**Issue by elgalu** [twisted/towncrier#353]
Hi, thanks for this nice tool, question,

Does it support [GitHub releases](https://github.com/github/hub) ? i.e. to automatically `hub release create -m ${MESSAGE} $(date +%Y%m%d%H%M%S)` with the same rst/markdown content that get's added to the Changelog? e.g.

```sh
# Create a GitHub Release from master using release notes from a file
# https://hub.github.com/hub-release.1.html
hub release create --copy -F release-notes.rst v2.3.0
```

**Comment by elgalu** [comment]
Actually it would probably be better to use the official <https://github.com/cli/cli>

```sh
gh release create 0.0.2 --title "# test gh release title" --notes "# test gh release notes" -F CHANGELOG.md dist/slurmops-0.0.1*
#=> https://github.com/elgalu/some-project/releases/tag/0.0.2
```

**Comment by webknjaz** [comment]
I suppose you could use `--draft` to get the contents of the unreleased notes in your release pipeline and then send that to GitHub releases.

**Comment by adiroiban** [comment]
I don't understand what is the requested functionality.

AFAIK, GitHub releases is just GitHub proprietary take on git annotated tags.

You can run towncrier to create the `release-notes.rst` file and then just call GitHub proprietary tools or API to create the release.

**Comment by webknjaz** [comment]
> AFAIK, GitHub releases is just GitHub proprietary take on git annotated tags.

It's actually a bit of a wrapper that is bound to a Git tag, may have an extra piece of markdown attached, a pre-release label and a linked gh discussion.

> You can run towncrier to create the `release-notes.rst` file and then just call GitHub proprietary tools or API to create the release.

I'd like to add that many people using RST would want to post-process it by converting Sphinx-specific roles into something simpler with `sed` and running `pandoc` on that to convert it into markdown since GH won't render the note as RST.

Check out https://github.com/ansible/pylibssh/blob/3b0beb1/.github/workflows/build-test-n-publish.yml#L469-L516 for an example of conversion and, as a bonus, also outputting it to the GH job summary like this: https://github.com/ansible/pylibssh/actions/runs/3705179529.
