### ISSUE TITLE
Drop python 2.7 and 3.5 support

### ISSUE THREAD

**Issue by saroad2** [twisted/towncrier#375]
As of today (March 23rd 2022) the Python Software Foundation (PSF) has dropped support of Python versions before Python 3.7 (ie. 2.7, 3.5 and 3.6).

I truly recommend that *Towncrier* should also drop support for those versions.
This will allow us to use advanced tools of python such as `dataclasses`, f-string, async methods etc.

**Comment by altendky** [comment]
If someone is doing an overhaul then it might be reasonable.  If towncrier is continuing in maintenance mode with limited resources then I would suggest waiting until 2.7 support is truly in the way.

From https://pypistats.org/packages/towncrier it does look mostly reasonable to drop 2.7 support, but there is a non-zero number of daily downloads.  Here's my commentary on 2.7 support elsewhere https://github.com/pytest-dev/pytest-twisted#python-2-support-plans.

**Comment by saroad2** [comment]
Hey @altendky.

In my personal experience, sometimes you need to draw a line in the sand and make a choice. I don't think that Python 2.7 downloads will ever reach to 0. There will always be people who would prefer avoiding change and would want to use an old version. That's the way people are.

I'm sorry to hear that *Towncrier* is in maintenance mode. I think there are a lot of great stuff to do with it to make it even better than it's already is.

I have an intension to start using *Towncrier* in my projects including [Eddington](https://github.com/EddLabs/eddington) and [Statue](https://github.com/saroad2/statue). I already made a PR in #374 for adding messages in command line. I would like to add some more abilities that I think would be beneficial.

**Comment by altendky** [comment]
Other people are more active lately than I have been.  Also, I didn't mean that any non-stop number of py2 downloads justified any amount of dev overhead.  Just that the boundary for dropping support should be higher than 'dataclasses are nice'.  Anyways, there's attrs for that.  But yes, I encourage people to move off old versions but realize some people are stuck for reasons outside their control and try to avoid gratuitously increasing their pain.  If there's active dev work and py2 support is in the way... Yeah, move on.

**Comment by adiroiban** [comment]
> I'm sorry to hear that Towncrier is in maintenance mode. I think there are a lot of great stuff to do with it to make it even better than it's already is.

No need to feel sorry. If you can help, the help is welcomed. Thanks :)

Towncrier is in "maintance" mode as there aren't that many developers doing reviews for PR submitted by other developers, running manual tests and discovering regressions, looking for preparing a release... etc.

For ex, I prepared the last release PR in Nov 2021, and until end of Jan 2022 nobody checked the PR and reported whether the release is ready to go.

---------

I have reviewed your PR. it looks good.

--------

I am still on py2.7 but if maintaining py2.7 is a showstopper  and PITA for towncrier's future development I am not -1 on dropping it.

I setup towncrier in 2017 and since then it just works. No need for upgrade :)

**Comment by saroad2** [comment]
> Towncrier is in "maintance" mode as there aren't that many developers doing reviews for PR submitted by other developers, running manual tests and discovering regressions, looking for preparing a release... etc.
>
> For ex, I prepared the last release PR in Nov 2021, and until end of Jan 2022 nobody checked the PR and reported whether the release is ready to go.

I intend on being more invested on *Towncrier* for the following months. I know several projects that use it regularly such as [Beeware](https://github.com/beeware), but I didn't have the chance to fully explore it until now. Maybe I can review some PRs if you link them here or send me links via mail.

> I am still on py2.7 but if maintaining py2.7 is a showstopper and PITA for towncrier's future development I am not -1 on dropping it.
>
> I setup towncrier in 2017 and since then it just works. No need for upgrade :)

In the case where there is a lack of developers and resources for this effort, I understand this approach. However, there is a tendency for code to rot when it is not updated regularly to use new syntaxes and abilities.

To demonstrate this concept, I mostly use the example of `dataclasses` that was introduces in Python 3.7 and can dramitaclly reduce code lines number. Projects that don't update to version 3.7 lose this amazing ability and have to write sometimes tens to hundreds of unnecessary code lines.

Updating as a value, not as a mean for an end, is something I truly believe as a software developer and I hope that you'll change your mind about it in the future.

Thank you for reviewing my PR and have a wonderful week!

**Comment by adiroiban** [comment]
I am not -1 on this.

But do we need async methods in towncrier ?

I like "f" strings :)

If there is a clear advantage of using dataclasses and this will propel towncrier to the GitHub stars, we can do it.


--------------

A well written code can also age like a fine wine :p

I think that towncrier code is not that bad and it's not rotten :)

It might be a victim of its own success.
It works so well that people forget about it.

**Comment by saroad2** [comment]
Maybe I came out too strong. I **really** don't think that *Towncrier*'s code is rotten. on the contrary: I think this is an awesome project that I wish got more attention to it.

**Comment by altendky** [comment]
I do tend to move forward, no need to convince me.  `:]`  Also, attrs.org...  a great example of why using third party libs is very useful.  `dataclasses` added in Python 3.7 in 2018 is a slow moving minimal copy of parts of attrs (which was available in 2015).  attrs still supports 2.7 and 3.5+ so it can be used here.  But sure, as long as 2.7 support sticks around here you have to use the more verbose form instead of hints.

I think the rot hazard comes from lack of attention more than lack of use of new features.  Anyways, I took a pass at catching up towncrier dev and getting a release out a year or two ago and certainly appreciate whoever takes on the next round of that.

Towards the end of avoiding rot, I just put in https://github.com/twisted/towncrier/pull/376.  If you have time for a review once I undraft it, that'd be great.  `:]`  There's also https://github.com/twisted/towncrier/pull/319, though that's still forward looking as tox v4 isn't released yet.

**Comment by adiroiban** [comment]
> It's also kinda a waste of computing power to have such an extensive build matrix, I'm trying to lead the way in attrs too. sweat_smile

Agree. Happy to see a PR that cuts on this.

-----

And if the support for python 2.7 and 3.6 is a blocker for contributing to towncrier I am +1 for removing support for it.

**Comment by adiroiban** [comment]
So...we dropped, support. The floodgates for py3 only PRs are open. Let them come :)

Thanks Hynek for the PRs.
