### ISSUE TITLE
`towncrier build` needs force removal

### ISSUE THREAD

**Issue by KonstantinKlepikov** [twisted/towncrier#403]
```sh
I want to remove the following files:
/home/myproject/newsfragments/3.feature
Is it okay if I remove those files? [Y/n]: y
error: the following file has changes staged in the index:
   myproject/newsfragments/3.feature
(use --cached to keep the file, or -f to force removal)
Done!
```

**Comment by adiroiban** [comment]
Thanks for the report 

Why you have staged fragment files ?

Is this related to https://github.com/twisted/towncrier/pull/357 ?

Note that towncrier development is not very active. If you want to have this fixed you will have to submit a pull request... otherwise, there is a low probability for someone else to work on fixing it.

**Comment by KonstantinKlepikov** [comment]
@adiroiban i stage it because another problem uccuped with untracked fragments: `fatal: pathspec ...did not match any files Done!`

related problem #60 and you recomended to this: 

> git add newsfragments\vue.misc before calling towncrier and it should work

**Comment by adiroiban** [comment]
My suggestion for #60 was for a file that was not tracked.

I guess that in your case, the initial error is cause by another reason.

Can you provide the steps that one can follow to reproduce your error?

Thanks

**Comment by KonstantinKlepikov** [comment]
@adiroiban sorry, my mistake. I tried create changelog before commit fragments. It's ok.
