### ISSUE TITLE
Release time?

### ISSUE THREAD

**Issue by SmileyChris** [twisted/towncrier#616]
We've got a big backlog of fixes in trunk now -- time for a release you think @adiroiban ?

Maybe #604 should be resolved first, but nothing else is outstanding. (if we do the precommit hooks updates, we should also update the version referenced in docs)

**Comment by adiroiban** [comment]
Hi. I think #604 can be merged. There was no other feedback from other devs.

Do you have time to check the release process and try to do the release your self - https://towncrier.readthedocs.io/en/latest/release.html

In this way, we can check that the release notes make sense and anyone can do a release.

Otherwise, I can also trigger the release, no problem.

thanks

**Comment by adiroiban** [comment]
I hope that we can have #622 merged by the end of the next week and then we can have a released.

@SmileyChris regarding #604 It looks line nobody else is interested in the `pre-commit` integration. I think that you can go ahead and make sure all checks pass on that PR and then we can have it merged.

 @bentheiii is there any particular feature that you want to have in the next release?
