### ISSUE TITLE
Allow wildcards in "ignore" configuration option

### ISSUE THREAD

**Issue by eigenbrot** [twisted/towncrier#642]
Since version 24.7.0 (and PR #622) there is an "ignore" configuration option that allows users to specify files that are known to have "wrong" filenames but still belong in the fragments directory.

It would be very helpful if this "ignore" option supported wildcards in filenames. For example:

```
[tool.towncrier]
    ignore = [".gitempty", "useful_file_num*.ext"]
```

Thanks!

**Comment by adiroiban** [comment]
Hi Arthur 

Thanks for the report.

Can you please add more information about your feature request.

What other files belong to the newsfragment directory ?

----------

I am happy to review and approve a PR that implementes simple glob expressions.

**Comment by eigenbrot** [comment]
Hi @adiroiban, thanks for the quick response.

In our use case we maintain two separate changelogs files for two different audiences; one that captures change to the codebase itself and one that reports on any scientific changes to the output of that code. We do this by maintaining two configuration TOML files that build the two changelogs, each with their own fragment types. We keep all of our fragments in the same "changelog" directory and so when running `towncrier check` for one changelog it now complains about the fragments from the other changelog.

As I'm writing that I'm realizing that we could also sidestep this issue by having two separate fragment directories, but that feels a bit more cumbersome than setting the ignore option to include `"*.other_changelog_fragment_name.rst"`. I also suspect that someone else will want wildcards at some point for a different reason.

**Comment by adiroiban** [comment]
The changes in `towncrier check` were design to detect non-fragment files from being created in the news fragment directory.

I would say that using 2 separate news fragment directories is the best way here.

------

To implement globbing the changes needs to go here


https://github.com/twisted/towncrier/blob/fc3a2556408bcdb0237e54c4ff0773db364c554a/src/towncrier/_builder.py#L144-L146

Instead of doing a simple string comparision, we should use https://docs.python.org/3/library/fnmatch.html#fnmatch.fnmatch  for each member of the ignore list

-------

If you have time, please consider creating a PR and I would be happy to review.

Thanks

**Comment by eigenbrot** [comment]
@adiroiban, thanks for pointing me in the right direction! PR #644 should be ready for review.
