### ISSUE TITLE
Separate deprecation category?

### ISSUE THREAD

**Issue by hynek** [twisted/towncrier#77]
I’m thinking of using towncrier in attrs but I’d *really* like to separate deprecations and actual removals/breaking changes into separate categories.  Is there a way to achieve that like thru customizing them?  I’d really prefer `breaking.id` over `removal.id` too since there’s more ways than just removal to break. :)

**Comment by hynek** [comment]
Wait, is https://github.com/hawkowl/towncrier/blob/master/pyproject.toml#L10-L33 freeform?  The readme sounds like there’s only a bunch of standard categories.  If I can do whatever the foobar I want, I’m changing this ticket to a doc bug. :)

**Comment by adiroiban** [comment]
You can have as many categories as you want.

And yes, the public documentation is not that great... you still need to read the code ... but is short :)


Here is my config

```
[tool.towncrier]

    STANDARD STUFF HERE


    [[tool.towncrier.type]]
        directory = "feature"
        name = "New Features"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "defect"
        name = "Defect Fixes"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "removal"
        name = "API Removals"
        showcontent = true


    [[tool.towncrier.type]]
        directory = "depracation"
        name = "Deprecations"
        showcontent = true

    [[tool.towncrier.type]]
        directory = "ignore"
        name = "Ignored"
        showcontent = false
```

-----------

and the `showcontent` part can be implemented as you like in the template.

Instead of 'misc' I name the fragments `1234.ignore` and in the template I am completely ignoring a type with showcontent = false

**Comment by hawkowl** [comment]
Yeah, this is a docs bug... *makes a note*

**Comment by SmileyChris** [comment]
Documented in configuration reference
